version: '3.1'

services:
  db:
    image: mysql:5.7.29
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    stdin_open: true
    tty: true
