version: '3.1'

services:
  db:
    image: mysql:5.7.29
    command: --init-file /data/application/init.sql
    volumes:
        - ./data/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    ports:
      - ${NODE_DOCKER_PORT}:${NODE_DOCKER_PORT}
    environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    stdin_open: true
    tty: true
